// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabletopOnlineAPI.Data.Contexts;

namespace TabletopOnlineAPI.Data.Migrations
{
    [DbContext(typeof(AppDatabase))]
    [Migration("20190210155225_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");
#pragma warning restore 612, 618
        }
    }
}
